Link NVIDIA application profiles
this was causing the error 

ERROR: nvidia-settings could not find the registry key file. This file should have been installed along with this driver at either /usr/share/nvidia/nvidia-application-profiles-440.64-key-documentation or
       /usr/share/nvidia/nvidia-application-profiles-key-documentation. The application profiles will continue to work, but values cannot be prepopulated or validated, and will not be listed in the help text. Please see the README for
       possible values and descriptions.